/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicineTypeAddDTO
 */
export interface MedicineTypeAddDTO {
    /**
     * 
     * @type {string}
     * @memberof MedicineTypeAddDTO
     */
    typeName?: string | null;
}

/**
 * Check if a given object implements the MedicineTypeAddDTO interface.
 */
export function instanceOfMedicineTypeAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineTypeAddDTOFromJSON(json: any): MedicineTypeAddDTO {
    return MedicineTypeAddDTOFromJSONTyped(json, false);
}

export function MedicineTypeAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineTypeAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typeName': !exists(json, 'typeName') ? undefined : json['typeName'],
    };
}

export function MedicineTypeAddDTOToJSON(value?: MedicineTypeAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'typeName': value.typeName,
    };
}

