/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicineCategoryAddDTO
 */
export interface MedicineCategoryAddDTO {
    /**
     * 
     * @type {string}
     * @memberof MedicineCategoryAddDTO
     */
    categoryName?: string | null;
}

/**
 * Check if a given object implements the MedicineCategoryAddDTO interface.
 */
export function instanceOfMedicineCategoryAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineCategoryAddDTOFromJSON(json: any): MedicineCategoryAddDTO {
    return MedicineCategoryAddDTOFromJSONTyped(json, false);
}

export function MedicineCategoryAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineCategoryAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryName': !exists(json, 'categoryName') ? undefined : json['categoryName'],
    };
}

export function MedicineCategoryAddDTOToJSON(value?: MedicineCategoryAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryName': value.categoryName,
    };
}

