/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MedicineDTO } from './MedicineDTO';
import {
    MedicineDTOFromJSON,
    MedicineDTOFromJSONTyped,
    MedicineDTOToJSON,
} from './MedicineDTO';

/**
 * 
 * @export
 * @interface MedicineDTOPagedResponse
 */
export interface MedicineDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof MedicineDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<MedicineDTO>}
     * @memberof MedicineDTOPagedResponse
     */
    data?: Array<MedicineDTO> | null;
}

/**
 * Check if a given object implements the MedicineDTOPagedResponse interface.
 */
export function instanceOfMedicineDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineDTOPagedResponseFromJSON(json: any): MedicineDTOPagedResponse {
    return MedicineDTOPagedResponseFromJSONTyped(json, false);
}

export function MedicineDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(MedicineDTOFromJSON)),
    };
}

export function MedicineDTOPagedResponseToJSON(value?: MedicineDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(MedicineDTOToJSON)),
    };
}

