/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { MedicineTypeDTO } from './MedicineTypeDTO';
import {
    MedicineTypeDTOFromJSON,
    MedicineTypeDTOFromJSONTyped,
    MedicineTypeDTOToJSON,
} from './MedicineTypeDTO';

/**
 * 
 * @export
 * @interface MedicineTypeDTORequestResponse
 */
export interface MedicineTypeDTORequestResponse {
    /**
     * 
     * @type {MedicineTypeDTO}
     * @memberof MedicineTypeDTORequestResponse
     */
    response?: MedicineTypeDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MedicineTypeDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the MedicineTypeDTORequestResponse interface.
 */
export function instanceOfMedicineTypeDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineTypeDTORequestResponseFromJSON(json: any): MedicineTypeDTORequestResponse {
    return MedicineTypeDTORequestResponseFromJSONTyped(json, false);
}

export function MedicineTypeDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineTypeDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : MedicineTypeDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MedicineTypeDTORequestResponseToJSON(value?: MedicineTypeDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': MedicineTypeDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

