/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicineAddDTO
 */
export interface MedicineAddDTO {
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    medicineName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    medicineDescription?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineAddDTO
     */
    medicinePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineAddDTO
     */
    medicineMeasurement?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicineAddDTO
     */
    quantity?: number;
    /**
     * 
     * @type {Date}
     * @memberof MedicineAddDTO
     */
    expiryDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    medicineTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    medicineCategoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineAddDTO
     */
    supplierId?: string;
}

/**
 * Check if a given object implements the MedicineAddDTO interface.
 */
export function instanceOfMedicineAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineAddDTOFromJSON(json: any): MedicineAddDTO {
    return MedicineAddDTOFromJSONTyped(json, false);
}

export function MedicineAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicineName': !exists(json, 'medicineName') ? undefined : json['medicineName'],
        'medicineDescription': !exists(json, 'medicineDescription') ? undefined : json['medicineDescription'],
        'medicinePrice': !exists(json, 'medicinePrice') ? undefined : json['medicinePrice'],
        'medicineMeasurement': !exists(json, 'medicineMeasurement') ? undefined : json['medicineMeasurement'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'expiryDate': !exists(json, 'expiryDate') ? undefined : (new Date(json['expiryDate'])),
        'image': !exists(json, 'image') ? undefined : json['image'],
        'medicineTypeId': !exists(json, 'medicineTypeId') ? undefined : json['medicineTypeId'],
        'medicineCategoryId': !exists(json, 'medicineCategoryId') ? undefined : json['medicineCategoryId'],
        'supplierId': !exists(json, 'supplierId') ? undefined : json['supplierId'],
    };
}

export function MedicineAddDTOToJSON(value?: MedicineAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medicineName': value.medicineName,
        'medicineDescription': value.medicineDescription,
        'medicinePrice': value.medicinePrice,
        'medicineMeasurement': value.medicineMeasurement,
        'quantity': value.quantity,
        'expiryDate': value.expiryDate === undefined ? undefined : (value.expiryDate.toISOString()),
        'image': value.image,
        'medicineTypeId': value.medicineTypeId,
        'medicineCategoryId': value.medicineCategoryId,
        'supplierId': value.supplierId,
    };
}

