/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicineTypeDTO
 */
export interface MedicineTypeDTO {
    /**
     * 
     * @type {string}
     * @memberof MedicineTypeDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineTypeDTO
     */
    typeName?: string | null;
}

/**
 * Check if a given object implements the MedicineTypeDTO interface.
 */
export function instanceOfMedicineTypeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineTypeDTOFromJSON(json: any): MedicineTypeDTO {
    return MedicineTypeDTOFromJSONTyped(json, false);
}

export function MedicineTypeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineTypeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'typeName': !exists(json, 'typeName') ? undefined : json['typeName'],
    };
}

export function MedicineTypeDTOToJSON(value?: MedicineTypeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'typeName': value.typeName,
    };
}

