/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { MedicineDTOPagedResponse } from './MedicineDTOPagedResponse';
import {
    MedicineDTOPagedResponseFromJSON,
    MedicineDTOPagedResponseFromJSONTyped,
    MedicineDTOPagedResponseToJSON,
} from './MedicineDTOPagedResponse';

/**
 * 
 * @export
 * @interface MedicineDTOPagedResponseRequestResponse
 */
export interface MedicineDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {MedicineDTOPagedResponse}
     * @memberof MedicineDTOPagedResponseRequestResponse
     */
    response?: MedicineDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MedicineDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the MedicineDTOPagedResponseRequestResponse interface.
 */
export function instanceOfMedicineDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MedicineDTOPagedResponseRequestResponseFromJSON(json: any): MedicineDTOPagedResponseRequestResponse {
    return MedicineDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function MedicineDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : MedicineDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MedicineDTOPagedResponseRequestResponseToJSON(value?: MedicineDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': MedicineDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

