/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupplierAddDTO
 */
export interface SupplierAddDTO {
    /**
     * 
     * @type {string}
     * @memberof SupplierAddDTO
     */
    supplierName?: string | null;
}

/**
 * Check if a given object implements the SupplierAddDTO interface.
 */
export function instanceOfSupplierAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SupplierAddDTOFromJSON(json: any): SupplierAddDTO {
    return SupplierAddDTOFromJSONTyped(json, false);
}

export function SupplierAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'supplierName': !exists(json, 'supplierName') ? undefined : json['supplierName'],
    };
}

export function SupplierAddDTOToJSON(value?: SupplierAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'supplierName': value.supplierName,
    };
}

