/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MedicineDTO } from './MedicineDTO';
import {
    MedicineDTOFromJSON,
    MedicineDTOFromJSONTyped,
    MedicineDTOToJSON,
} from './MedicineDTO';

/**
 * 
 * @export
 * @interface SupplierDTO
 */
export interface SupplierDTO {
    /**
     * 
     * @type {string}
     * @memberof SupplierDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierDTO
     */
    supplierName?: string | null;
    /**
     * 
     * @type {MedicineDTO}
     * @memberof SupplierDTO
     */
    medicine?: MedicineDTO;
}

/**
 * Check if a given object implements the SupplierDTO interface.
 */
export function instanceOfSupplierDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SupplierDTOFromJSON(json: any): SupplierDTO {
    return SupplierDTOFromJSONTyped(json, false);
}

export function SupplierDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'supplierName': !exists(json, 'supplierName') ? undefined : json['supplierName'],
        'medicine': !exists(json, 'medicine') ? undefined : MedicineDTOFromJSON(json['medicine']),
    };
}

export function SupplierDTOToJSON(value?: SupplierDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'supplierName': value.supplierName,
        'medicine': MedicineDTOToJSON(value.medicine),
    };
}

