/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { SupplierDTO } from './SupplierDTO';
import {
    SupplierDTOFromJSON,
    SupplierDTOFromJSONTyped,
    SupplierDTOToJSON,
} from './SupplierDTO';

/**
 * 
 * @export
 * @interface SupplierDTORequestResponse
 */
export interface SupplierDTORequestResponse {
    /**
     * 
     * @type {SupplierDTO}
     * @memberof SupplierDTORequestResponse
     */
    response?: SupplierDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof SupplierDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the SupplierDTORequestResponse interface.
 */
export function instanceOfSupplierDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SupplierDTORequestResponseFromJSON(json: any): SupplierDTORequestResponse {
    return SupplierDTORequestResponseFromJSONTyped(json, false);
}

export function SupplierDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : SupplierDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function SupplierDTORequestResponseToJSON(value?: SupplierDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': SupplierDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

